package com.cabify.demo.ui.theme

import androidx.compose.ui.graphics.Color

// Generate them via theme builder
// https://material-foundation.github.io/material-theme-builder/#/custom

val cabifyLightPrimary = Color(0xFF825500)
val cabifyLightOnPrimary = Color(0xFFFFFFFF)
val cabifyLightPrimaryContainer = Color(0xFFFFDDAE)
val cabifyLightOnPrimaryContainer = Color(0xFF2A1800)
val cabifyLightSecondary = Color(0xFF6F5B40)
val cabifyLightOnSecondary = Color(0xFFFFFFFF)
val cabifyLightSecondaryContainer = Color(0xFFFADEBC)
val cabifyLightOnSecondaryContainer = Color(0xFF271904)
val cabifyLightTertiary = Color(0xFF516440)
val cabifyLightOnTertiary = Color(0xFFFFFFFF)
val cabifyLightTertiaryContainer = Color(0xFFD3EABC)
val cabifyLightOnTertiaryContainer = Color(0xFF102004)
val cabifyLightError = Color(0xFFBA1B1B)
val cabifyLightErrorContainer = Color(0xFFFFDAD4)
val cabifyLightOnError = Color(0xFFFFFFFF)
val cabifyLightOnErrorContainer = Color(0xFF410001)
val cabifyLightBackground = Color(0xFFFCFCFC)
val cabifyLightOnBackground = Color(0xFF1F1B16)
val cabifyLightSurface = Color(0xFFFCFCFC)
val cabifyLightOnSurface = Color(0xFF1F1B16)
val cabifyLightSurfaceVariant = Color(0xFFF0E0CF)
val cabifyLightOnSurfaceVariant = Color(0xFF4F4539)
val cabifyLightOutline = Color(0xFF817567)
val cabifyLightInverseOnSurface = Color(0xFFF9EFE6)
val cabifyLightInverseSurface = Color(0xFF34302A)
val cabifyLightPrimaryInverse = Color(0xFFFFB945)

val cabifyDarkPrimary = Color(0xFFFFB945)
val cabifyDarkOnPrimary = Color(0xFF452B00)
val cabifyDarkPrimaryContainer = Color(0xFF624000)
val cabifyDarkOnPrimaryContainer = Color(0xFFFFDDAE)
val cabifyDarkSecondary = Color(0xFFDDC3A2)
val cabifyDarkOnSecondary = Color(0xFF3E2E16)
val cabifyDarkSecondaryContainer = Color(0xFF56442B)
val cabifyDarkOnSecondaryContainer = Color(0xFFFADEBC)
val cabifyDarkTertiary = Color(0xFFB8CEA2)
val cabifyDarkOnTertiary = Color(0xFF243516)
val cabifyDarkTertiaryContainer = Color(0xFF3A4C2B)
val cabifyDarkOnTertiaryContainer = Color(0xFFD3EABC)
val cabifyDarkError = Color(0xFFFFB4A9)
val cabifyDarkErrorContainer = Color(0xFF930006)
val cabifyDarkOnError = Color(0xFF680003)
val cabifyDarkOnErrorContainer = Color(0xFFFFDAD4)
val cabifyDarkBackground = Color(0xFF1F1B16)
val cabifyDarkOnBackground = Color(0xFFEAE1D9)
val cabifyDarkSurface = Color(0xFF1F1B16)
val cabifyDarkOnSurface = Color(0xFFEAE1D9)
val cabifyDarkSurfaceVariant = Color(0xFF4F4539)
val cabifyDarkOnSurfaceVariant = Color(0xFFD3C4B4)
val cabifyDarkOutline = Color(0xFF9C8F80)
val cabifyDarkInverseOnSurface = Color(0xFF32281A)
val cabifyDarkInverseSurface = Color(0xFFEAE1D9)
val cabifyDarkPrimaryInverse = Color(0xFF624000)
