object CoreDependencies {
    const val appCompat = "androidx.appcompat:appcompat:${Versions.appCompat}"
    const val coreKtx = "androidx.core:core-ktx:${Versions.coreKtx}"
    const val converterGson = "com.squareup.retrofit2:converter-gson:${Versions.converterGson}"
    const val fragmentKtx = "androidx.navigation:navigation-fragment-ktx:${Versions.fragmentKtx}"
    const val okhttp = "com.squareup.okhttp3:okhttp:${Versions.okhttp}"
    const val liveDataKtx = "androidx.lifecycle:lifecycle-livedata-ktx:${Versions.liveDataKtx}"
    const val navigationKtx = "androidx.navigation:navigation-ui-ktx:${Versions.navigationKtx}"
    const val koinAndroid = "io.insert-koin:koin-android:${Versions.koinAndroid}"
    const val viewModelKtx = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.viewModelKtx}"
    const val benManes = "com.github.ben-manes.versions"
    const val rxAndroid3 = "io.reactivex.rxjava3:rxandroid:${Versions.rxAndroid3}"
    const val rxJava3 = "io.reactivex.rxjava3:rxjava:${Versions.rxjava3}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val roomRuntime = "androidx.room:room-runtime:${Versions.room}"
    const val roomCompiler = "androidx.room:room-compiler:${Versions.room}"
    const val roomRxJava3 = "androidx.room:room-rxjava3:${Versions.room}"
    const val retrofitRx3Adapter =
        "com.squareup.retrofit2:adapter-rxjava3:${Versions.retrofitRx3Adapter}"
    const val mockitoKotlin = "org.mockito.kotlin:mockito-kotlin:${Versions.mockitoKotlin}"
}