object Versions {
    const val appCompat = "1.6.0"
    const val benManes = "0.42.0"
    const val coreKtx = "1.9.0"
    const val constraintLayout = "2.1.4"
    const val converterGson = "2.9.0"
    const val espresso = "3.5.1"
    const val fragmentKtx = "2.5.3"
    const val gradle = "7.2.2"
    const val jUnitExt = "1.1.5"
    const val jUnit = "4.13.2"
    const val kotlin = "1.7.0"
    const val koinAndroid= "3.3.2"
    const val liveDataKtx = "2.5.1"
    const val navigationKtx = "2.5.3"
    const val material = "1.7.0"
    const val viewModelKtx = "2.5.1"
    const val retrofit = "2.9.0"
    const val retrofitRx3Adapter = "2.9.0"
    const val rxAndroid3 = "3.0.0"
    const val rxjava3 = "3.1.5"
    const val okhttp = "4.10.0"
}